apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "awstestapplication-020623"
  description: "awstestapplication-020623"

  links:
    - url: https://github.com/RohanAwasthi/awstestapplication-020623
      title: "awstestapplication-020623"
      icon: code

  labels:
    system: web-apps
    trackid: "awstestapplication-020623"
    environmentname: my-python-env-020623

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-awstestapplication-020623'
    github.com/project-slug: RohanAwasthi/awstestapplication-020623
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "neelesh.shekhar"
